includes = ['./.alca.*.toml']
image = 'debian:bookworm-slim'

workdir_exclude = [
  ".alca*",
  ".mise.local.toml",
  "__pycache__",
]

mounts = [
  ".alca.cache/mise:/root/.local/share/mise",
]

[resources]
memory = "16g"
cpus = 8

[commands]
# prepare the environment
up = """
apt update -y && \
apt install -y curl && \
install -dm 755 /etc/apt/keyrings && \
curl -fSs https://mise.jdx.dev/gpg-key.pub | tee /etc/apt/keyrings/mise-archive-keyring.asc 1> /dev/null && \
echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.asc] https://mise.jdx.dev/deb stable main" | tee /etc/apt/sources.list.d/mise.list && \
apt update -y && 
apt install -y mise

# other tools
apt install -y vim tmux git

echo '
export LANG=C.UTF-8
export LC_ALL=C.UTF-8
export PATH="/root/.local/share/mise/shims:$PATH"
[ -x /extra-scripts/source.sh ] && . /extra-scripts/source.sh
' >> ~/.bashrc
. ~/.bashrc

mise trust
mise install

[ -x /extra-scripts/init.sh ] && /extra-scripts/init.sh
"""
