# Alcatraz Preset Source: git+https://github.com/bolasblack/alcatraz.git#a1e11d8e42490a14dce7437babfcb464b77a396e:.alca.claude.toml
#:schema https://raw.githubusercontent.com/bolasblack/alcatraz/refs/heads/master/alca-config.schema.json

mounts = [
  "${HOME}/.claude/CLAUDE.md:/root/.claude/CLAUDE.md",
  "${HOME}/.claude/skills:/root/.claude/skills",
  "${HOME}/.claude/commands:/root/.claude/commands",
  "${HOME}/.claude/agents:/root/.claude/agents",
  "${HOME}/.claude/output-styles:/root/.claude/output-styles",
  "${HOME}/.claude/plugins:/root/.claude/plugins",

  "${HOME}/.claude/tasks:/root/.claude/tasks",
]