includes = ['./.alca.*.toml']
image = 'ghcr.io/bolasblack/alca-debian:latest'

workdir_exclude = [
  ".alca*",
  ".mise.local.toml",
  "__pycache__",
]

mounts = [
  '.alca.mounts/mise:/mise',
  '.alca.mounts/extra-bin:/extra-bin',
  '.alca.mounts/extra-scripts:/extra-scripts'
]

[resources]
memory = "16g"
cpus = 8

[envs]
IS_SANDBOX = '1'

[commands]
up = """
apt install -y vim tmux

echo '
export PATH="/extra-bin:/mise/shims/:$PATH"
' >> ~/.profile
. ~/.profile

[ -x /extra-scripts/source.sh ] && . /extra-scripts/source.sh

mise trust -a
mise install

[ -x /extra-scripts/init.sh ] && /extra-scripts/init.sh
"""
enter = """
[ -x /extra-scripts/source.sh ] && . /extra-scripts/source.sh
. ~/.profile
"""
